-- MySQL Schema untuk Universal CMS & Hotel Management System
-- Mendukung fitur dinamis (WordPress-like) dan modul spesifik (Hotel)

SET FOREIGN_KEY_CHECKS = 0;

-- 1. USER MANAGEMENT
DROP TABLE IF EXISTS `User`;
CREATE TABLE `User` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `email` VARCHAR(191) NOT NULL UNIQUE,
  `password` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NOT NULL,
  `role` VARCHAR(191) NOT NULL DEFAULT 'admin',
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX `User_email_idx` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. CONTENT ENGINE (The "WordPress" Way)
DROP TABLE IF EXISTS `Post`;
CREATE TABLE `Post` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `title` VARCHAR(191) NOT NULL,
  `titleEn` VARCHAR(191) NULL,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `content` LONGTEXT NULL,
  `contentEn` LONGTEXT NULL,
  `excerpt` TEXT NULL,
  `excerptEn` TEXT NULL,
  `featuredImage` VARCHAR(191) NULL,
  `postType` VARCHAR(191) NOT NULL DEFAULT 'post', -- 'post', 'page', 'room', 'service'
  `status` VARCHAR(191) NOT NULL DEFAULT 'publish',
  `categoryId` VARCHAR(191) NULL,
  `authorId` VARCHAR(191) NOT NULL,
  `views` INT NOT NULL DEFAULT 0,
  `order` INT NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX `Post_slug_idx` (`slug`),
  INDEX `Post_postType_idx` (`postType`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `PostMeta`;
CREATE TABLE `PostMeta` (
  `id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `postId` VARCHAR(191) NOT NULL,
  `metaKey` VARCHAR(191) NOT NULL,
  `metaValue` LONGTEXT NULL,
  INDEX `PostMeta_postId_idx` (`postId`),
  INDEX `PostMeta_metaKey_idx` (`metaKey`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. FRONT PAGE COMPONENTS (Specific Tables for Fast Access)
DROP TABLE IF EXISTS `Slider`;
CREATE TABLE `Slider` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `title` VARCHAR(191) NOT NULL,
  `titleEn` VARCHAR(191) NULL,
  `subtitle` VARCHAR(191) NULL,
  `subtitleEn` VARCHAR(191) NULL,
  `image` VARCHAR(191) NULL,
  `videoUrl` VARCHAR(191) NULL,
  `videoFile` VARCHAR(191) NULL,
  `videoDuration` INT NULL,
  `buttonText` VARCHAR(191) NULL,
  `buttonTextEn` VARCHAR(191) NULL,
  `buttonUrl` VARCHAR(191) NULL,
  `order` INT NOT NULL DEFAULT 0,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `HomeSection`;
CREATE TABLE `HomeSection` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `type` VARCHAR(191) NOT NULL, -- 'hero', 'about', 'services', 'video-profile', etc.
  `title` VARCHAR(191) NULL,
  `titleEn` VARCHAR(191) NULL,
  `subtitle` VARCHAR(191) NULL,
  `subtitleEn` VARCHAR(191) NULL,
  `content` LONGTEXT NULL,
  `contentEn` LONGTEXT NULL,
  `image` VARCHAR(191) NULL,
  `imageLeft` VARCHAR(191) NULL,
  `imageRight` VARCHAR(191) NULL,
  `images` TEXT NULL, -- JSON array
  `videoUrl` VARCHAR(191) NULL,
  `buttonText` VARCHAR(191) NULL,
  `buttonTextEn` VARCHAR(191) NULL,
  `buttonUrl` VARCHAR(191) NULL,
  `faqItems` TEXT NULL, -- JSON array
  `figures` TEXT NULL, -- JSON array
  `partnerships` TEXT NULL, -- JSON array
  `mapEmbedUrl` TEXT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4. TAXONOMY & MENUS
DROP TABLE IF EXISTS `Category`;
CREATE TABLE `Category` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `nameEn` VARCHAR(191) NULL,
  `slug` VARCHAR(191) NOT NULL UNIQUE,
  `description` TEXT NULL,
  `parentId` VARCHAR(191) NULL,
  `categoryType` VARCHAR(191) NOT NULL DEFAULT 'general',
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Menu`;
CREATE TABLE `Menu` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `title` VARCHAR(191) NOT NULL,
  `titleEn` VARCHAR(191) NULL,
  `slug` VARCHAR(191) NOT NULL,
  `parentId` VARCHAR(191) NULL,
  `order` INT NOT NULL DEFAULT 0,
  `menuType` VARCHAR(191) NOT NULL DEFAULT 'link',
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5. HOTEL MODULE
DROP TABLE IF EXISTS `Booking`;
CREATE TABLE `Booking` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `roomId` VARCHAR(191) NOT NULL,
  `guestName` VARCHAR(191) NOT NULL,
  `guestEmail` VARCHAR(191) NULL,
  `guestPhone` VARCHAR(191) NULL,
  `checkIn` DATETIME NOT NULL,
  `checkOut` DATETIME NOT NULL,
  `totalPrice` DECIMAL(15,2) NOT NULL DEFAULT 0,
  `status` VARCHAR(191) NOT NULL DEFAULT 'booked',
  `notes` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 6. CORE CMS TABLES
DROP TABLE IF EXISTS `Media`;
CREATE TABLE `Media` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `filename` VARCHAR(191) NOT NULL,
  `url` VARCHAR(191) NOT NULL,
  `mimeType` VARCHAR(191) NOT NULL,
  `size` INT NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Setting`;
CREATE TABLE `Setting` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `key` VARCHAR(191) NOT NULL UNIQUE,
  `value` TEXT NOT NULL,
  `valueEn` TEXT NULL,
  `type` VARCHAR(191) NOT NULL DEFAULT 'text',
  `group` VARCHAR(191) NOT NULL DEFAULT 'general',
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 7. ADDITIONAL TABLES (Required by existing controllers)
DROP TABLE IF EXISTS `FAQ`;
CREATE TABLE `FAQ` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `question` TEXT NOT NULL,
  `questionEn` TEXT NULL,
  `answer` TEXT NOT NULL,
  `answerEn` TEXT NULL,
  `order` INT NOT NULL DEFAULT 0,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Figure`;
CREATE TABLE `Figure` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `role` VARCHAR(191) NULL,
  `roleEn` VARCHAR(191) NULL,
  `image` VARCHAR(191) NULL,
  `order` INT NOT NULL DEFAULT 0,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Partnership`;
CREATE TABLE `Partnership` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `name` VARCHAR(191) NOT NULL,
  `image` VARCHAR(191) NULL,
  `url` VARCHAR(191) NULL,
  `order` INT NOT NULL DEFAULT 0,
  `isActive` BOOLEAN NOT NULL DEFAULT TRUE,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `SEO`;
CREATE TABLE `SEO` (
  `id` VARCHAR(191) NOT NULL PRIMARY KEY,
  `pageType` VARCHAR(191) NOT NULL, -- 'global', 'post', 'page'
  `targetId` VARCHAR(191) NULL,
  `title` VARCHAR(191) NULL,
  `description` TEXT NULL,
  `keywords` VARCHAR(191) NULL,
  `ogImage` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
